// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"index":{"path":"/","id":"index"}},
    routeComponents: {
'index': React.lazy(() => import(/* webpackChunkName: "p__index" */'../../pages/index.tsx')),
},
  };
}
